# This file was generated by 'fetch_pin'. Do not edit directly!
import (builtins.fetchTarball {
  name = "nixos-20.09";
  url =
    "https://github.com/nixos/nixpkgs/archive/65c9cc79f1d179713c227bf447fb0dac384cdcda.tar.gz";
  sha256 = "0whxlm098vas4ngq6hm3xa4mdd2yblxcl5x5ny216zajp08yp1wf";
})
